name: "Run Example"
description: "Run example projects"
author: "AriPerkkio"
inputs:
  example-name:
    required: true
    description: "Name of the example project"
  node-version:
    required: true
    description: "Node version for setup-node"
  vitest-version:
    required: true
    description: "Vitest version to use"

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2

    - uses: ./.github/actions/setup-and-cache
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install & Build
      shell: bash
      run: |
        pnpm install
        pnpm build

    - name: Run ${{ inputs.example-name }} with vitest@${{ inputs.vitest-version }}
      working-directory: ./examples/${{ inputs.example-name }}
      shell: bash
      run: |
        pnpm install
        pnpm install -D vitest@${{ inputs.vitest-version }}
        pnpm test
