name: 'Run Example'
description: 'Run example projects'
author: 'AriPerkkio'
inputs:
    example-name:
        required: true
        description: 'Name of the example project'

    node-version:
        required: true
        description: 'Node version for setup-node'
runs:
    using: 'composite'
    steps:
        - name: Install pnpm
          uses: pnpm/action-setup@v2

        - uses: ./.github/actions/setup-and-cache
          with:
              node-version: ${{ inputs.node-version }}

        - uses: actions/download-artifact@v3
          with:
              name: built-package

        - name: Build and test ${{ inputs.example-name }}
          working-directory: ./examples/${{ inputs.example-name }}
          shell: bash
          run: |
              pnpm install
              pnpm test
