name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14, 16]

        steps:
            - uses: actions/checkout@v2

            - uses: ./.github/actions/setup-and-cache
              with:
                  node-version: ${{ matrix.node-version }}
